- .gitmodules
- Cargo.lock
- Cargo.toml
- package-lock.json
- package.json
- packages/ironfish-native-module/rust_lib/Cargo.toml
Until ironfish-rust is published as a crate, we can submodule the repository and build it from source so we're all working against the same version of ironfish-rust.
The submodule should be initialized by a postinstall script after running `npm install` in the root of the repository.
Fixes IFL-2362
> Add ironfish repository as submodule

- Cargo.lock
- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/Cargo.toml
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/shims/ironfish-rust-nodejs.js
Allows us to decode all account formats using decodeAccount from the SDK.
Fixes IFL-2425
Fixes IFL-2427
Fixes IFL-2454
> Fix decodeAccount in SDK

- package-lock.json
- packages/mobile-app/app.json
- packages/mobile-app/app/(tabs)/transact.tsx
- packages/mobile-app/data/facades/accounts/demoHandlers.ts
- packages/mobile-app/data/facades/accounts/handlers.ts
- packages/mobile-app/data/facades/accounts/types.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/index.ts
- packages/mobile-app/package.json
Demonstrates using expo-secure-store to store the spend key, and exportAccount to output the account + spend key.
exportAccount isn't complete yet, will add more parameters to make it similar to the RPC's version.
> Demo using secure store with exportAccount

- packages/mobile-app/app/(tabs)/contacts.tsx
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/globals.ts
- packages/mobile-app/index.js
We've occasionally run into problems with globals not actually being polyfilled for some reason. I saw it recommended here to load polyfills before expo-router: https://github.com/expo/expo/discussions/25122#discussioncomment-7433169
> Load globals before expo-router

- packages/mobile-app/data/facades/wallet/demoHandlers.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
The facade supports fetching a single transaction, and we should be able to return that now (barring fields that haven't been implemented yet)
Fixes IFL-2770
> Implement getTransaction in wallet

- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/data/facades/wallet/demoHandlers.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
Update getTransactions facade handler to fetch transactions by account name.
Fixes IFL-2771
> Fetch transactions by account name

- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/data/wallet/writeCache.ts
Initial pass on scanning for spent notes and nullifiers, and saving them to the database along with account balances.
Fixes IFL-2768
Fixes IFL-2769
> Save nullifiers and balances to database

- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/data/api/walletServer.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
Adds the confirmed balance to the Wallet `getBalances` function. Pending and Available will come once we have transaction creation ready to go.
Fixes IFL-2836
> Add confirmed balance

- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/data/wallet/writeCache.ts
The current WriteCache writes the account head and the transactions in separate DB calls. Merging them should be more efficient, plus avoid a broken state if one of the writes fails.
Fixes IFL-2839
> Update account head and add transactions in a single DB transaction

- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/app/send/index.tsx
- packages/mobile-app/data/wallet/wallet.ts
This aligns behavior of the mobile wallet with that of the standalone wallet, but we should probably be fetching the transaction version from the wallet-server instead of the SDK. That would make it easier to ship activation sequence hardforks.
Fixes IFL-2902
> Pass in transaction version from SDK

- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/app/send/index.tsx
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
WAL mode is generally faster, and I don't think any of the listed downsides apply: https://www.sqlite.org/draft/wal.html So opting to default to enabling WAL mode and can disable if we run into issues on Android/iOS.
> Enable WAL mode in SQLite

- .gitmodules
- Cargo.lock
- package-lock.json
- package.json
- packages/ironfish-native-module/rust_lib/Cargo.toml
Uses the recently updated Rust crate instead of a submodule for building the native module.
> Use Rust crate instead of submodule

- packages/mobile-app/app.json
- packages/mobile-app/app/menu/debug/index.tsx
- packages/mobile-app/app/menu/debug/oreowallet.tsx
- packages/mobile-app/data/facades/index.ts
- packages/mobile-app/data/oreowalletServerApi/oreowalletServerApi.ts
- packages/mobile-app/data/wallet/wallet.ts
Adds a debug page as well as an implementation of the oreowallet API. Tested importing an account, fetching balances/transactions, and creating an account with locally-generated proofs.
For now we'll generate proofs on-device since that's already built. To use the proving server, we'd need to update the Iron Fish rust crate to support adding proofs to an existing transaction.
> Add Oreowallet server API

- packages/mobile-app/app/(tabs)/balances.tsx
- packages/tackle-box/lib/components/Tabs/Tabs.tsx
- packages/tackle-box/lib/components/Text/Text.tsx
- packages/tackle-box/lib/index.ts
- packages/tackle-box/lib/vars/colors.stylex.ts
> Add Tabs component

- packages/tackle-box/lib/components/Box/Box.tsx
- packages/tackle-box/lib/components/Polymorphic/Polymorphic.tsx
Lets us override the returned component type for Box
> Add Polymorphic component, update Box to use it

- package-lock.json
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/menu/debug/index.tsx
- packages/mobile-app/app/menu/debug/oreowallet.tsx
- packages/mobile-app/data/api/api.ts
- packages/mobile-app/data/api/types.ts
- packages/mobile-app/data/facades/wallet/demoHandlers.ts
- packages/mobile-app/data/facades/wallet/oreowalletHandlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/facades/wallet/walletServerHandlers.ts
- packages/mobile-app/data/oreowalletServerApi/oreowalletServerApi.ts
- packages/mobile-app/data/wallet/oreowalletWallet.ts
- packages/mobile-app/package.json
Generates the oreowallet auth header and adds it to calls.
Fixed since PR was opened:
> Add oreowallet auth header to calls

- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/account-select/index.tsx
- packages/mobile-app/app/account-settings/index.tsx
- packages/mobile-app/app/send/index.tsx
Uses the SDK's currency rendering function to display balances with the right number of decimals.
Note that this doesn't yet apply to the inputs on the Send form -- since this is still WIP, I left it as-is, but happy to help implement when we get to that.
Also, removed fee estimation since oreowallet doesn't support it currently.
> Use SDK currency rendering functions

- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/data/constants.ts
- packages/mobile-app/data/oreowalletServerApi/oreowalletServerApi.ts
- packages/mobile-app/data/wallet/oreowalletWallet.ts
- packages/mobile-app/data/wallet/wallet.ts
Spent a bit thinking about adding support for this into the wallet class directly, but I'd like to avoid having to make another call to oreowallet for the account head, so I think the simplest approach will work fine for now
> Hide scanning message when account head is within CONFIRMATIONS of latest

- packages/mobile-app/app/menu/debug/oreowallet.tsx
- packages/mobile-app/app/menu/network/index.tsx
- packages/mobile-app/data/facades/chain/demoHandlers.ts
- packages/mobile-app/data/facades/chain/oreowalletHandlers.ts
- packages/mobile-app/data/facades/chain/types.ts
- packages/mobile-app/data/facades/chain/walletServerHandlers.ts
- packages/mobile-app/data/facades/wallet/oreowalletHandlers.ts
- packages/mobile-app/data/wallet/db.ts
Adds support for switching between mainnet and testnet.
I currently have it re-import all accounts when switching between networks. I modified account import to do nothing if an account with the same public address exists in the database, but this does introduce some edge cases where someone imports the same account with a different name, or same account plus/minus the spend key. Nothing will happen now, where previously we'd throw an error.
> Support switching between mainnet and testnet

- package-lock.json
- packages/ironfish-native-module/android/src/main/java/expo/modules/ironfishnativemodule/IronfishNativeModule.kt
- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/app/(drawer)/app-settings/debug/oreowallet.tsx
- packages/mobile-app/data/debug/reverseScan.ts
- packages/mobile-app/data/facades/wallet/oreowalletHandlers.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/oreowalletWallet.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/package.json
- packages/mobile-app/shims/ironfish-rust-nodejs.js
Updates the Iron Fish SDK to 2.10.0. This will require running `npm i` from the root directory, as well as rebuilding the rust code (Should be handled automatically by `nx ios` or `nx android`).
> Update ironfish SDK to 2.10.0

- packages/mobile-app/app/(drawer)/account/account-settings/account-select/index.tsx
- packages/mobile-app/app/(drawer)/account/account-settings/add-account/create.tsx
- packages/mobile-app/app/(drawer)/account/account-settings/add-account/index.tsx
- packages/mobile-app/app/(drawer)/account/account-settings/export-account/index.tsx
- packages/mobile-app/app/(drawer)/account/account-settings/index.tsx
- packages/mobile-app/app/(drawer)/account/index.tsx
- packages/mobile-app/app/(drawer)/account/send/index.tsx
- packages/mobile-app/app/(drawer)/account/transaction/[hash].tsx
- packages/mobile-app/app/(drawer)/app-settings/debug/index.tsx
- packages/mobile-app/app/(drawer)/app-settings/debug/oreowallet.tsx
- packages/mobile-app/app/(drawer)/app-settings/debug/pending.tsx
- packages/mobile-app/app/(drawer)/app-settings/debug/unspent.tsx
- packages/mobile-app/app/(drawer)/app-settings/index.tsx
- packages/mobile-app/app/(drawer)/app-settings/network/index.tsx
- packages/mobile-app/app/_layout.tsx
React navigation was switching to dark theme (as well as the status bar), but ui-kitten is hardcoded to use light theme. Fixing the dark theme will take some effort, so for now we can just hardcode everything to light theme.
> Hardcode light theme for react navigation
