iron-fish/mobile-wallet

- Cargo.lock
- packages/ironfish-native-module/android/src/main/java/expo/modules/ironfishnativemodule/IronfishNativeModule.kt
- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/Cargo.toml
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/App.tsx
Adds generateKey and generateKeyFromPrivateKey to the Rust library.
Fixes IFL-2413
Fixes IFL-2414
> Add generateKey and generateKeyFromPrivateKey

- package-lock.json
- packages/mobile-app/app.json
- packages/mobile-app/app/(tabs)/_layout.tsx
- packages/mobile-app/app/(tabs)/contacts.tsx
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/(tabs)/transact.tsx
- packages/mobile-app/app/_layout.tsx
- packages/mobile-app/package.json
Adds Expo Navigation and stubs out main tabs
> Add Expo Navigation

- Cargo.lock
- package-lock.json
- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/Cargo.toml
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/scripts/cargo-android.ts
- packages/ironfish-native-module/scripts/cargo-ios.ts
- packages/ironfish-native-module/src/index.ts
- packages/ironfish-native-module/uniffi-bindgen/Cargo.toml
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/(tabs)/transact.tsx
- packages/mobile-app/app/_layout.tsx
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/data/wallet/writeCache.ts
Decrypts notes and saves related transactions to the DB. Note that this isn't complete -- we'll still want to check if the notes have been spent, and use that to determine the balance.
> Save transactions to DB

- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/mobile-app/app.json
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/data/api/walletServer.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/data/wallet/writeCache.ts
Saves known notes to the database.
Fixes IFL-2764
> Save notes to database

- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
Adds the transaction type to account transactions.
Fixes IFL-2837
> Add transaction type to accountTransaction

- packages/mobile-app/app/(tabs)/contacts.tsx
- packages/mobile-app/data/blockchain.ts
- packages/mobile-app/data/chainProcessor.ts
- packages/mobile-app/data/facades/wallet/demoHandlers.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/wallet/wallet.ts
Add support for pausing and resuming scanning, as well as checking the wallet status.
Fixes IFL-2767
> Support pausing and resuming scanning

- .github/workflows/ci.yml
- package.json
- packages/data-facade/package.json
- packages/ironfish-native-module/package.json
- packages/mobile-app/package.json
- packages/ui-kit/package.json
Run TypeScript type checking in CI lint phase.
> Typecheck in CI

- packages/mobile-app/app/(tabs)/contacts.tsx
- packages/mobile-app/data/debug/README.md
- packages/mobile-app/data/debug/reverseChainProcessor.ts
- packages/mobile-app/data/debug/reverseScan.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/data/wallet/writeQueue.ts
Adds support for removing blocks from the database. Also added a `debug` folder with some tools for rolling back the chain to test this.
Fixes IFL-2824
> Support removing blocks from the DB

- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/_layout.tsx
- packages/mobile-app/app/account-select.tsx
- packages/mobile-app/app/account-settings/remove-account.tsx
- packages/mobile-app/app/add-account/create.tsx
- packages/mobile-app/app/add-account/import-encoded.tsx
- packages/mobile-app/app/onboarding/create.tsx
- packages/mobile-app/app/onboarding/import-encoded.tsx
- packages/mobile-app/app/onboarding/index.tsx
- packages/mobile-app/data/facades/wallet/demoHandlers.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
Allows you to use the account select screen to mark an account as active.
Fixes IFL-2861
> Add support for setting an account as active

- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/menu/debug/index.tsx
- packages/mobile-app/data/debug/reverseScan.ts
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
Account head and account balances were both missing from getAccount and getAccounts, respectively, so this adds those fields back in.
> Fix account head and balances

- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/data/wallet/wallet.ts
Still have to hook up fee rate fetching, but expiration and fee are now passed through to the transaction creation process.
Fixes IFL-2908
> Add expiration and fee to createTransaction

- Cargo.lock
- packages/ironfish-native-module/ios/IronfishNativeModule.swift
- packages/ironfish-native-module/rust_lib/Cargo.toml
- packages/ironfish-native-module/rust_lib/src/lib.rs
- packages/ironfish-native-module/src/index.ts
- packages/mobile-app/app/(tabs)/index.tsx
- packages/mobile-app/app/_layout.tsx
- packages/mobile-app/app/account-settings/account-name.tsx
- packages/mobile-app/app/menu/debug/index.tsx
- packages/mobile-app/app/menu/debug/pending.tsx
- packages/mobile-app/app/menu/debug/unspent.tsx
- packages/mobile-app/app/send/index.tsx
- packages/mobile-app/data/facades/wallet/handlers.ts
- packages/mobile-app/data/wallet/db.ts
- packages/mobile-app/data/wallet/wallet.ts
- packages/mobile-app/data/wallet/writeQueue.ts
- packages/mobile-app/data/walletServerApi/transformers/forkTester.ts
- packages/mobile-app/data/walletServerApi/types.ts
- packages/mobile-app/data/walletServerApi/walletServer.ts
- packages/mobile-app/shims/ironfish-rust-nodejs.js
Adds support for creating and broadcasting transactions, saving the pending ones to the DB, then updating them when they appear onchain.
Fixes IFL-2900
Fixes IFL-2899
> Set up creating and sending transactions

- packages/ironfish-native-module/android/build.gradle
- packages/ironfish-native-module/android/src/main/java/expo/modules/ironfishnativemodule/IronfishNativeModule.kt
- packages/mobile-app/project.json
Fixes native module support on Android to support the same functions as iOS. I'm not totally sure these implementations are idiomatic (throwing exceptions in the right way, etc.) but I verified that all of the functions work as expected.
> Fix native module support on Android

- package-lock.json
- packages/mobile-app/app/(tabs)/balances.tsx
- packages/mobile-app/app/_layout.tsx
- packages/tackle-box/lib/components/BottomSheet/BottomSheet.tsx
- packages/tackle-box/lib/index.ts
- packages/tackle-box/package.json
Adds utility to show bottom sheets
> Add bottom sheet

- packages/mobile-app/app/(tabs)/_layout.tsx
- packages/mobile-app/data/facades/index.ts
I added an incorrect cast-to-boolean at the last moment that ended up not working... Fixed this so that the EXPO_PUBLIC_DEMO_API environment variable works right. I also added some error handling to make sure it throws an error if the values are out-of-range.
Also fixed the title casing of the Balances tab.
> Fix DEMO_API environment variable

- package-lock.json
- packages/mobile-app/app/_layout.tsx
- packages/mobile-app/app/onboarding/index.tsx
- packages/mobile-app/components/LinkButton.tsx
- packages/mobile-app/package.json
> Adds tamagui basic config and updates LinkButton

- LICENSE
- package.json
- packages/data-facade/package.json
- packages/mobile-app/package.json
Adds LICENSE and updates projects' package.json to include author and license
> Add LICENSE and author where missing

- packages/mobile-app/app/onboarding/import-encoded.tsx
> Adds import by encoded key

- packages/mobile-app/app/onboarding/create-pin.tsx
Uses the setAppSetting facade to save the PIN on the PIN creation screen.
> Save PIN on pin creation screen

- packages/mobile-app/app/_layout.tsx
- packages/mobile-app/app/onboarding/create-pin.tsx
- packages/mobile-app/components/PinInputComponent.tsx
- packages/mobile-app/components/PinLockScreen/PinLockScreen.tsx
- packages/mobile-app/data/facades/app/demoHandlers.ts
> Add PIN lock screen

- packages/mobile-app/app/account-settings/index.tsx
- packages/mobile-app/data/facades/app/demoHandlers.ts
- packages/mobile-app/data/facades/app/walletServerHandlers.ts
- packages/mobile-app/data/settings/db.ts
Adds a setting for hiding the balances, and wires up the toggle on the account menu page.
> Add setting for hiding balances

- packages/mobile-app/app/(tabs)/index.tsx
Let's defer building the per-asset transactions page until we have everything else done.
> Remove arrow from list of asset balances

- packages/mobile-app/app/(drawer)/account/account-settings/export-account/index.tsx
Tests account export formats using the facade.
> Test account exporting

- packages/mobile-app/app/(drawer)/account/account-settings/account-name/index.tsx
> Style the Account Name screen with ui-kitten

- packages/mobile-app/app/(drawer)/account/index.tsx
- packages/mobile-app/components/account/AssetRow.tsx
- packages/mobile-app/components/account/TransactionRow.tsx
- packages/mobile-app/data/facades/wallet/types.ts
- packages/mobile-app/svgs/ReceiveArrow.tsx
- packages/mobile-app/svgs/SendArrow.tsx
- packages/mobile-app/utils/currency.ts
Style the rows in the transactions list.
> Style transaction rows
